version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: dt-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: admin_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d admin_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: dt-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped

    # ================= KEYCLOAK DATABASE =================

  keycloak-db:
    image: postgres:16-alpine
    container_name: dt-keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    restart: unless-stopped

  # ================= KEYCLOAK =================

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: dt-keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8082:8080"
    depends_on:
      - keycloak-db
    restart: unless-stopped

  leads-generator:
    build: ./Back/Leads_Generator
    container_name: dt-leads-generator
    env_file:
      - ./Back/Leads_Generator/.env
    ports:
      - "5000:5000"
    restart: unless-stopped

volumes:
  pgdata:
  keycloak_data:
