spring.application.name=Lead-Intelligence-System

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/lead_management

spring.datasource.username=postgres
spring.datasource.password=anas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.cloud.discovery.enabled=true
eureka.client.service-url.defaultZone=${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}

# On active tous les endPoints de actuator
management.endpoints.web.exposure.include=*
# pour avoir les adresses IP et non pas les noms
eureka.instance.prefer-ip-address=true