spring.application.name=Admin

spring.datasource.url=jdbc:postgresql://localhost:5432/Admin
spring.datasource.username=postgres
<<<<<<< HEAD
spring.datasource.password=postgres
=======
spring.datasource.password=anas
>>>>>>> 2c1127f38027d2a0d4c8858ff1d6e1b7fc7ad70e

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

# JWT
app.jwt.secret=jahsjgdJHJWEYWDBYU127357352548SSG
app.jwt.expiration=86400000
